# Generated by Django 4.2.6 on 2023-10-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('bug_type', models.CharField(max_length=20)),
                ('report_date', models.DateTimeField(verbose_name='date reported')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
